[package]
org = "xlibb"
name = "solace.semp"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Solace", "Management"]
icon = "icon.png"
repository = "https://github.com/xlibb/module-solace.semp"
distribution = "2201.13.0"

[build-options]
observabilityIncluded = true
